/// Flutter icons MyFlutterApp
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
///
///
import 'package:flutter/widgets.dart';

class VerkerIcons {
  VerkerIcons._();

  static const _kFontFam = 'FlatIcon';
  static const String? _kFontPkg = null;

  static const IconData home =
      IconData(0xf1ec, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData settings =
      IconData(0xf27b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter =
      IconData(0xf1bf, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData slider =
      IconData(0xf27a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile =
      IconData(0xf2e1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData signedDocument =
      IconData(0xf19b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData project =
      IconData(0xf19c, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData chat =
      IconData(0xf1ab, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData picture =
      IconData(0xf246, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData video =
      IconData(0xf1be, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera =
      IconData(0xf14e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData signOut =
      IconData(0xf28e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData company =
      IconData(0xf143, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData projectSwipe =
      IconData(0xf25e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
