// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsIsswkcH9MBsHmsZMDTepLjFo325m6Hs',
    appId: '1:643913329272:web:827e17bf3a28ef370c9b8d',
    messagingSenderId: '643913329272',
    projectId: 'verker-prof',
    authDomain: 'verker-prof.firebaseapp.com',
    storageBucket: 'verker-prof.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD28xtTrhr_evyu_bUzkSlAjy25rwm0-vM',
    appId: '1:643913329272:android:c614d692c00738320c9b8d',
    messagingSenderId: '643913329272',
    projectId: 'verker-prof',
    storageBucket: 'verker-prof.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1_IQJqbn17ADgwIj8zZTvqY4VEelQz4U',
    appId: '1:643913329272:ios:ad123647d992b2ea0c9b8d',
    messagingSenderId: '643913329272',
    projectId: 'verker-prof',
    storageBucket: 'verker-prof.appspot.com',
    iosClientId: '643913329272-vjfjgegvkae1u9jl5mnb1d991ejm0s7b.apps.googleusercontent.com',
    iosBundleId: 'dk.verker.verkerprof',
  );
}
